<a href="https://colab.research.google.com/github/HarshShetye/Djs_Compute_Task/blob/main/ML_Task_5_SVM_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Q1 Import and explore the data
Dataset Link: https://drive.google.com/file/d/1tPHOMKD_ef-j8MuynCn2fSpbrL11-J1l/view?usp=sharing

In [19]:
import pandas as pd
import numpy as np

In [20]:
df = pd.read_csv("pulsar.txt", sep=",")
df

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve,target_class
0,121.156250,48.372971,0.375485,-0.013165,3.168896,18.399367,7.449874,65.159298,0.0
1,76.968750,36.175557,0.712898,3.388719,2.399666,17.570997,9.414652,102.722975,0.0
2,130.585938,53.229534,0.133408,-0.297242,2.743311,22.362553,8.508364,74.031324,0.0
3,156.398438,48.865942,-0.215989,-0.171294,17.471572,NaN,2.958066,7.197842,0.0
4,84.804688,36.117659,0.825013,3.274125,2.790134,20.618009,8.405008,76.291128,0.0
...,...,...,...,...,...,...,...,...,...
12523,124.312500,53.179053,-0.012418,-0.556021,7.186455,29.308266,4.531382,21.725143,0.0
12524,115.617188,46.784600,0.218177,0.226757,6.140468,NaN,5.732201,34.357283,0.0
12525,116.031250,43.213846,0.663456,0.433088,0.785117,11.628149,17.055215,312.204325,0.0
12526,135.664062,49.933749,-0.089940,-0.226726,3.859532,21.501505,7.398395,62.334018,0.0
12527,120.726562,50.472256,0.346178,0.184797,0.769231,11.792603,17.662222,329.548016,0.0

In [21]:
df.isnull().sum()

 Mean of the integrated profile                     0
 Standard deviation of the integrated profile       0
 Excess kurtosis of the integrated profile       1735
 Skewness of the integrated profile                 0
 Mean of the DM-SNR curve                           0
 Standard deviation of the DM-SNR curve          1178
 Excess kurtosis of the DM-SNR curve                0
 Skewness of the DM-SNR curve                     625
target_class                                        0
dtype: int64

In [22]:
df.describe()

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve,target_class
count,12528.000000,12528.000000,10793.000000,12528.000000,12528.000000,11350.000000,12528.000000,11903.000000,12528.000000
mean,111.041841,46.521437,0.478548,1.778431,12.674758,26.351318,8.333489,105.525779,0.092034
std,25.672828,6.801077,1.064708,6.208450,29.613230,19.610842,4.535783,107.399585,0.289085
min,5.812500,24.772042,-1.738021,-1.791886,0.213211,7.370432,-3.139270,-1.976976,0.000000
25%,100.871094,42.362222,0.024652,-0.188142,1.910535,14.404353,5.803063,35.199899,0.000000
50%,115.183594,46.931022,0.223678,0.203317,2.792642,18.412402,8.451097,83.126301,0.000000
75%,127.109375,50.979103,0.473125,0.932374,5.413253,28.337418,10.727927,139.997850,0.000000
max,189.734375,91.808628,8.069522,68.101622,222.421405,110.642211,34.539844,1191.000837,1.000000

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12528 entries, 0 to 12527
Data columns (total 9 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0    Mean of the integrated profile                12528 non-null  float64
 1    Standard deviation of the integrated profile  12528 non-null  float64
 2    Excess kurtosis of the integrated profile     10793 non-null  float64
 3    Skewness of the integrated profile            12528 non-null  float64
 4    Mean of the DM-SNR curve                      12528 non-null  float64
 5    Standard deviation of the DM-SNR curve        11350 non-null  float64
 6    Excess kurtosis of the DM-SNR curve           12528 non-null  float64
 7    Skewness of the DM-SNR curve                  11903 non-null  float64
 8   target_class                                   12528 non-null  float64
dtypes: float64(9)
memory usage: 881.0 KB

##Q2 Carry out data pre-processing

In [24]:
df.dropna(axis=0,inplace=True)

##Q3 Split the data in traina and test set

In [25]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

##Q4 Scale the data using Standard Scaler

####Q4a According to you, why is scaling important in SVM? What are the different methods for scaling the data available in sklearn.preprocessing?

Ans: The range of values of data may vary widely hence it becomes necessary step to standardize the range of features of data in SVM.


MinMaxScaler.

In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

##Q5 Implement SVM

Different types of kernels in SVM:
https://www.kaggle.com/discussions/questions-and-answers/326336

###Q5a Linear SVM

Apply Linear SVM for costs (C) = [0.1, 1, 10, 100, 1000], predict for the test set and check f1 score for each of the costs. State the best cost

In [28]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
param_grid = {'C': [0.1,1, 10, 100]} 
grid_search = GridSearchCV(estimator = classifier,scoring='f1_micro',param_grid = param_grid,refit=2,verbose=2)
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
[CV] END ..............................................C=0.1; total time=   0.1s
[CV] END ..............................................C=0.1; total time=   0.1s
[CV] END ..............................................C=0.1; total time=   0.1s
[CV] END ..............................................C=0.1; total time=   0.1s
[CV] END ..............................................C=0.1; total time=   0.1s
[CV] END ................................................C=1; total time=   0.1s
[CV] END ................................................C=1; total time=   0.1s
[CV] END ................................................C=1; total time=   0.1s
[CV] END ................................................C=1; total time=   0.1s
[CV] END ................................................C=1; total time=   0.1s
[CV] END ...............................................C=10; total time=   0.3s
[CV] END ...............................................C=10; total time=   0.2s
[CV] END ...............................................C=10; total time=   0.2s
[CV] END ...............................................C=10; total time=   0.2s
[CV] END ...............................................C=10; total time=   0.2s
[CV] END ..............................................C=100; total time=   1.1s
[CV] END ..............................................C=100; total time=   1.0s
[CV] END ..............................................C=100; total time=   0.9s
[CV] END ..............................................C=100; total time=   0.7s
[CV] END ..............................................C=100; total time=   1.0s

GridSearchCV(estimator=SVC(kernel='linear', random_state=0),
             param_grid={'C': [0.1, 1, 10, 100]}, refit=2, scoring='f1_micro',
             verbose=2)

In [29]:
pd.DataFrame(grid_search.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.075942,0.007900,0.012702,0.000464,0.1,{'C': 0.1},0.977714,0.982746,0.978433,0.974119,0.974101,0.977423,0.003206,4
1,0.082276,0.005569,0.011872,0.000625,1,{'C': 1},0.979152,0.984184,0.977714,0.976995,0.975540,0.978717,0.002971,3
2,0.219268,0.030073,0.013097,0.002312,10,{'C': 10},0.979152,0.983465,0.978433,0.976995,0.975540,0.978717,0.002679,2
3,0.926730,0.107487,0.012677,0.002519,100,{'C': 100},0.979871,0.983465,0.978433,0.976995,0.975540,0.978861,0.002717,1

Here 100 is the Best Cost

###Q5b Polynomial Kernel

Apply Linear SVM for degrees = [1,2,3,4,5], predict for the test set and check f1 score for each of the degrees. State the best degree.

In [30]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
classifier = SVC(kernel = 'poly', random_state = 0)
param_grid = {'degree': [1,2,3,4,5]} 
grid_search = GridSearchCV(estimator = classifier,scoring='f1_micro',param_grid = param_grid,refit=2,verbose=2)
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits
[CV] END ...........................................degree=1; total time=   0.1s
[CV] END ...........................................degree=1; total time=   0.1s
[CV] END ...........................................degree=1; total time=   0.1s
[CV] END ...........................................degree=1; total time=   0.1s
[CV] END ...........................................degree=1; total time=   0.1s
[CV] END ...........................................degree=2; total time=   0.1s
[CV] END ...........................................degree=2; total time=   0.1s
[CV] END ...........................................degree=2; total time=   0.1s
[CV] END ...........................................degree=2; total time=   0.1s
[CV] END ...........................................degree=2; total time=   0.1s
[CV] END ...........................................degree=3; total time=   0.2s
[CV] END ...........................................degree=3; total time=   0.2s
[CV] END ...........................................degree=3; total time=   0.2s
[CV] END ...........................................degree=3; total time=   0.2s
[CV] END ...........................................degree=3; total time=   0.2s
[CV] END ...........................................degree=4; total time=   0.3s
[CV] END ...........................................degree=4; total time=   0.3s
[CV] END ...........................................degree=4; total time=   0.2s
[CV] END ...........................................degree=4; total time=   0.2s
[CV] END ...........................................degree=4; total time=   0.3s
[CV] END ...........................................degree=5; total time=   0.5s
[CV] END ...........................................degree=5; total time=   0.5s
[CV] END ...........................................degree=5; total time=   0.5s
[CV] END ...........................................degree=5; total time=   0.3s
[CV] END ...........................................degree=5; total time=   0.4s

GridSearchCV(estimator=SVC(kernel='poly', random_state=0),
             param_grid={'degree': [1, 2, 3, 4, 5]}, refit=2,
             scoring='f1_micro', verbose=2)

In [31]:
pd.DataFrame(grid_search.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_degree,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.081853,0.006893,0.013667,0.000715,1,{'degree': 1},0.977714,0.983465,0.978433,0.974838,0.974820,0.977854,0.003167,1
1,0.110346,0.012280,0.015795,0.001152,2,{'degree': 2},0.974838,0.976995,0.974119,0.971244,0.971942,0.973828,0.002067,3
2,0.177977,0.022206,0.015013,0.001575,3,{'degree': 3},0.976995,0.979871,0.976276,0.974119,0.974820,0.976416,0.002006,2
3,0.248420,0.026700,0.014725,0.000205,4,{'degree': 4},0.971963,0.976276,0.973400,0.972682,0.972662,0.973397,0.001510,4
4,0.413402,0.086010,0.014092,0.000381,5,{'degree': 5},0.971963,0.976276,0.970525,0.973400,0.970504,0.972534,0.002156,5

Best degree: 1

###Q5c Sigmoid Kernel

Apply Linear SVM for costs (C) = [0.1, 1, 10, 100, 1000], predict for the test set and check f1 score for each of the costs. State the best cost

In [32]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
classifier = SVC(kernel = 'sigmoid', random_state = 0)
param_grid = {'C': [0.1, 1, 10, 100, 1000]} 
grid_search = GridSearchCV(estimator = classifier,scoring='f1_micro',param_grid = param_grid, refit=2,verbose=2)
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits
[CV] END ..............................................C=0.1; total time=   0.4s
[CV] END ..............................................C=0.1; total time=   0.4s
[CV] END ..............................................C=0.1; total time=   0.4s
[CV] END ..............................................C=0.1; total time=   0.4s
[CV] END ..............................................C=0.1; total time=   0.4s
[CV] END ................................................C=1; total time=   0.4s
[CV] END ................................................C=1; total time=   0.4s
[CV] END ................................................C=1; total time=   0.4s
[CV] END ................................................C=1; total time=   0.4s
[CV] END ................................................C=1; total time=   0.4s
[CV] END ...............................................C=10; total time=   0.4s
[CV] END ...............................................C=10; total time=   0.4s
[CV] END ...............................................C=10; total time=   0.4s
[CV] END ...............................................C=10; total time=   0.4s
[CV] END ...............................................C=10; total time=   0.4s
[CV] END ..............................................C=100; total time=   0.4s
[CV] END ..............................................C=100; total time=   0.4s
[CV] END ..............................................C=100; total time=   0.4s
[CV] END ..............................................C=100; total time=   0.4s
[CV] END ..............................................C=100; total time=   0.4s
[CV] END .............................................C=1000; total time=   0.4s
[CV] END .............................................C=1000; total time=   0.4s
[CV] END .............................................C=1000; total time=   0.4s
[CV] END .............................................C=1000; total time=   0.4s
[CV] END .............................................C=1000; total time=   0.4s

GridSearchCV(estimator=SVC(kernel='sigmoid', random_state=0),
             param_grid={'C': [0.1, 1, 10, 100, 1000]}, refit=2,
             scoring='f1_micro', verbose=2)

In [33]:
pd.DataFrame(grid_search.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.354485,0.009403,0.079917,0.003371,0.1,{'C': 0.1},0.879224,0.882818,0.867721,0.872753,0.869065,0.874316,0.005829,1
1,0.341492,0.016694,0.075675,0.006552,1,{'C': 1},0.874191,0.882099,0.864845,0.865564,0.862590,0.869858,0.007280,2
2,0.339988,0.013923,0.069850,0.001130,10,{'C': 10},0.874191,0.881380,0.863408,0.865564,0.861151,0.869139,0.007547,3
3,0.332508,0.010728,0.072062,0.002902,100,{'C': 100},0.873472,0.881380,0.863408,0.865564,0.861151,0.868995,0.007456,4
4,0.334429,0.012084,0.070704,0.002633,1000,{'C': 1000},0.873472,0.881380,0.863408,0.865564,0.861151,0.868995,0.007456,4

0.1 is the Best Cost

###Q5d RBF Kernel

Apply Linear SVM for costs (C) = [0.1, 1, 10, 100, 1000], predict for the test set and check f1 score for each of the costs. State the best cost

In [34]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
param_grid = {'C': [0.1, 1, 10, 100, 1000]} 
grid_search = GridSearchCV(estimator = classifier,scoring='f1_micro',param_grid = param_grid,refit=2, verbose=2)
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits
[CV] END ..............................................C=0.1; total time=   0.2s
[CV] END ..............................................C=0.1; total time=   0.2s
[CV] END ..............................................C=0.1; total time=   0.2s
[CV] END ..............................................C=0.1; total time=   0.2s
[CV] END ..............................................C=0.1; total time=   0.2s
[CV] END ................................................C=1; total time=   0.2s
[CV] END ................................................C=1; total time=   0.2s
[CV] END ................................................C=1; total time=   0.2s
[CV] END ................................................C=1; total time=   0.2s
[CV] END ................................................C=1; total time=   0.2s
[CV] END ...............................................C=10; total time=   0.2s
[CV] END ...............................................C=10; total time=   0.2s
[CV] END ...............................................C=10; total time=   0.2s
[CV] END ...............................................C=10; total time=   0.2s
[CV] END ...............................................C=10; total time=   0.3s
[CV] END ..............................................C=100; total time=   0.4s
[CV] END ..............................................C=100; total time=   0.4s
[CV] END ..............................................C=100; total time=   0.4s
[CV] END ..............................................C=100; total time=   0.4s
[CV] END ..............................................C=100; total time=   0.4s
[CV] END .............................................C=1000; total time=   1.2s
[CV] END .............................................C=1000; total time=   1.1s
[CV] END .............................................C=1000; total time=   1.2s
[CV] END .............................................C=1000; total time=   1.1s
[CV] END .............................................C=1000; total time=   1.3s

GridSearchCV(estimator=SVC(random_state=0),
             param_grid={'C': [0.1, 1, 10, 100, 1000]}, refit=2,
             scoring='f1_micro', verbose=2)

In [35]:
pd.DataFrame(grid_search.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.167366,0.006526,0.051983,0.004003,0.1,{'C': 0.1},0.976276,0.979152,0.977714,0.971244,0.970504,0.974978,0.003480,5
1,0.150944,0.005596,0.034096,0.002081,1,{'C': 1},0.976995,0.982746,0.978433,0.974838,0.973381,0.977279,0.003239,3
2,0.188926,0.025717,0.032042,0.002620,10,{'C': 10},0.979871,0.982027,0.977714,0.976276,0.974820,0.978142,0.002561,1
3,0.348562,0.021314,0.033357,0.005493,100,{'C': 100},0.979871,0.982027,0.974838,0.975557,0.975540,0.977567,0.002856,2
4,1.137566,0.104607,0.030798,0.001974,1000,{'C': 1000},0.976276,0.982027,0.971244,0.976276,0.974820,0.976129,0.003476,4